name: currency_converter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  formz: ^0.8.0
  http: ^1.4.0
  loader_overlay: ^5.0.0
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        # Black:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        # Extra Bold:
        - asset: assets/fonts/Roboto-ExtraBold.ttf
          weight: 800
        # Bold:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        # Semi Bold:
        - asset: assets/fonts/Roboto-SemiBold.ttf
          weight: 600
        # Medium:
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        # Regular:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        # Light:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        # Extra Light:
        - asset: assets/fonts/Roboto-ExtraLight.ttf
          weight: 200
        # Thin:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100

  uses-material-design: true
